export const routes = {
  WELCOME: '/(auth)/welcome',
  LOGIN: '/(auth)/login',
  VERIFY_PHONE: '/(auth)/verify-phone',
  HOME: '/(main)/home',
  SELECT_RIDE: '/(main)/booking/select-ride',
  CONFIRM_BOOKING: '/(main)/booking/confirm',
  HOURLY_BOOKING: '/(main)/booking/hourly',
  MATCHING: '/(main)/matching',
  TRACKING: '/(main)/tracking',
  DRIVER_ARRIVED: '/(main)/driver-arrived',
  TRIP_ACTIVE: '/(main)/trip-active',
  TRIP_COMPLETE: '/(main)/trip-complete',
  SCHEDULE: '/(main)/schedule',
  HISTORY: '/(main)/history',
  PROFILE: '/(main)/profile',
  EMERGENCY_CONTACT: '/(main)/emergency-contact',
  PAYMENT: '/(main)/payment',
  NOTIFICATIONS: '/(main)/notifications',
  SUPPORT: '/(main)/support',
} as const;
